from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from dnsforge.infrastructure.bind.layout import BindLayout


@dataclass(frozen=True)
class TemplateArtifact:
    """Logical BIND artifact generated by DNSForge from a registered template."""

    key: str
    template: Path
    redhat_path: Path
    mode: int = 0o640

    def destination(self, layout: BindLayout) -> Path:
        from dnsforge.infrastructure.templates.service import TemplateService

        return TemplateService(layout=layout).destination_for(self.redhat_path)


class TemplateRegistry:
    """Central registry of BIND templates used by the hybrid renderer.

    Every .j2/.tpl file under infrastructure/templates/bind must be referenced
    here. This prevents orphan templates while keeping the modular BIND layout
    readable and distribution-aware.
    """

    ARTIFACTS: tuple[TemplateArtifact, ...] = (
        TemplateArtifact("named.conf", Path("bind/named.conf.j2"), Path("/etc/named.conf")),
        TemplateArtifact("acl", Path("bind/00-acl.conf.j2"), Path("/etc/named/conf.d/00-acl.conf")),
        TemplateArtifact("keys", Path("bind/10-keys.conf.j2"), Path("/etc/named/conf.d/10-keys.conf")),
        TemplateArtifact("options", Path("bind/20-options.conf.j2"), Path("/etc/named/conf.d/20-options.conf")),
        TemplateArtifact("logging", Path("bind/30-logging.conf.j2"), Path("/etc/named/conf.d/30-logging.conf")),
        TemplateArtifact("controls", Path("bind/40-controls.conf.j2"), Path("/etc/named/conf.d/40-controls.conf")),
        TemplateArtifact("statistics", Path("bind/45-statistics.conf.j2"), Path("/etc/named/conf.d/45-statistics.conf")),
        TemplateArtifact("rpz", Path("bind/50-rpz.conf.j2"), Path("/etc/named/conf.d/50-rpz.conf")),
        TemplateArtifact("views", Path("bind/60-views.conf.j2"), Path("/etc/named/conf.d/60-views.conf")),
        TemplateArtifact("rndc-key", Path("bind/10-keys.conf.j2"), Path("/etc/named/tsig/rndc.key")),
        TemplateArtifact("catalog-zone", Path("bind/catalog.zone.j2"), Path("/etc/named/catalog/catalog.zone")),
        TemplateArtifact("internal-zone-index", Path("bind/60-views.conf.j2"), Path("/etc/named/views/internal/zones.enabled/zones.index.conf")),
        TemplateArtifact("external-zone-index", Path("bind/60-views.conf.j2"), Path("/etc/named/views/external/zones.enabled/zones.index.conf")),
        TemplateArtifact("internal-master-template", Path("bind/master-zone.conf.tpl"), Path("/etc/named/views/internal/templates/master.conf.tpl")),
        TemplateArtifact("internal-secondary-template", Path("bind/secondary-zone.conf.tpl"), Path("/etc/named/views/internal/templates/secondary.conf.tpl")),
        TemplateArtifact("internal-forward-template", Path("bind/forward-zone.conf.tpl"), Path("/etc/named/views/internal/templates/forward.conf.tpl")),
        TemplateArtifact("external-master-template", Path("bind/master-zone.conf.tpl"), Path("/etc/named/views/external/templates/master.conf.tpl")),
        TemplateArtifact("external-secondary-template", Path("bind/secondary-zone.conf.tpl"), Path("/etc/named/views/external/templates/secondary.conf.tpl")),
        TemplateArtifact("external-forward-template", Path("bind/forward-zone.conf.tpl"), Path("/etc/named/views/external/templates/forward.conf.tpl")),
        TemplateArtifact("rpz-zone", Path("bind/rpz.local.zone.j2"), Path("/var/named/rpz/rpz.local.zone")),
    )

    @classmethod
    def keys(cls) -> tuple[str, ...]:
        return tuple(artifact.key for artifact in cls.ARTIFACTS)

    @classmethod
    def templates(cls) -> tuple[Path, ...]:
        return tuple(dict.fromkeys(artifact.template for artifact in cls.ARTIFACTS))

    @classmethod
    def destinations(cls, layout: BindLayout) -> tuple[Path, ...]:
        return tuple(artifact.destination(layout) for artifact in cls.ARTIFACTS)

    @classmethod
    def by_key(cls, key: str) -> TemplateArtifact:
        for artifact in cls.ARTIFACTS:
            if artifact.key == key:
                return artifact
        raise KeyError(key)
