#!/usr/bin/env bash
set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# Proxy HA templates are generated by Python services; no static HA templates are kept under infrastructure/bind/rendering.
test ! -d "${PROJECT_ROOT}/src/dnsforge/infrastructure/bind/rendering/dns-proxy"
echo "Proxy HA syntax validation OK"
