from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from dnsforge.infrastructure.bind.layout import BindLayout


@dataclass(frozen=True)
class TemplateArtifact:
    """Logical BIND artifact generated by DNSForge from a registered template."""

    key: str
    template: Path
    redhat_path: Path
    mode: int = 0o640

    def destination(self, layout: BindLayout) -> Path:
        from dnsforge.infrastructure.bind.rendering.template_service import TemplateService

        return TemplateService(layout=layout).destination_for(self.redhat_path)


class TemplateRegistry:
    """Central registry of BIND templates used by the hybrid renderer.

    Every .j2/.tpl file under infrastructure/bind/resources must be referenced
    here. This prevents orphan templates while keeping the modular BIND layout
    readable and distribution-aware.
    """

    ARTIFACTS: tuple[TemplateArtifact, ...] = (
        TemplateArtifact("named.conf", Path("named.conf.j2"), Path("/etc/named.conf")),
        TemplateArtifact("acl", Path("00-acl.conf.j2"), Path("/etc/named/conf.d/00-acl.conf")),
        TemplateArtifact("keys", Path("10-keys.conf.j2"), Path("/etc/named/conf.d/10-keys.conf")),
        TemplateArtifact("options", Path("20-options.conf.j2"), Path("/etc/named/conf.d/20-options.conf")),
        TemplateArtifact("logging", Path("30-logging.conf.j2"), Path("/etc/named/conf.d/30-logging.conf")),
        TemplateArtifact("controls", Path("40-controls.conf.j2"), Path("/etc/named/conf.d/40-controls.conf")),
        TemplateArtifact("statistics", Path("45-statistics.conf.j2"), Path("/etc/named/conf.d/45-statistics.conf")),
        TemplateArtifact("rpz", Path("50-rpz.conf.j2"), Path("/etc/named/conf.d/50-rpz.conf")),
        TemplateArtifact("catalog-conf", Path("55-catalog.conf.j2"), Path("/etc/named/conf.d/55-catalog.conf")),
        TemplateArtifact("views", Path("60-views.conf.j2"), Path("/etc/named/conf.d/60-views.conf")),
        TemplateArtifact("rndc-key", Path("10-keys.conf.j2"), Path("/etc/named/tsig/rndc.key")),
        TemplateArtifact("catalog-zone", Path("catalog.zone.j2"), Path("/etc/named/catalog/catalog.zone")),
        TemplateArtifact("internal-zone-index", Path("60-views.conf.j2"), Path("/etc/named/views/internal/zones.enabled/zones.index.conf")),
        TemplateArtifact("external-zone-index", Path("60-views.conf.j2"), Path("/etc/named/views/external/zones.enabled/zones.index.conf")),
        TemplateArtifact("internal-master-template", Path("master-zone.conf.tpl"), Path("/etc/named/views/internal/templates/master.conf.tpl")),
        TemplateArtifact("internal-secondary-template", Path("secondary-zone.conf.tpl"), Path("/etc/named/views/internal/templates/secondary.conf.tpl")),
        TemplateArtifact("internal-forward-template", Path("forward-zone.conf.tpl"), Path("/etc/named/views/internal/templates/forward.conf.tpl")),
        TemplateArtifact("external-master-template", Path("master-zone.conf.tpl"), Path("/etc/named/views/external/templates/master.conf.tpl")),
        TemplateArtifact("external-secondary-template", Path("secondary-zone.conf.tpl"), Path("/etc/named/views/external/templates/secondary.conf.tpl")),
        TemplateArtifact("external-forward-template", Path("forward-zone.conf.tpl"), Path("/etc/named/views/external/templates/forward.conf.tpl")),
        TemplateArtifact("rpz-zone", Path("rpz.local.zone.j2"), Path("/var/named/rpz/rpz.local.zone")),

        # Zone declaration templates are intentionally registered per server profile and scope.
        # Some files currently share content; the split is a product contract that prevents
        # authoritative, forwarder and hybrid policies from regressing into one generic template.
        TemplateArtifact("authoritative-internal-master-zone-template", Path("zones/authoritative/internal/master.conf.tpl"), Path("/etc/named/views/internal/templates/authoritative-master.conf.tpl")),
        TemplateArtifact("authoritative-internal-secondary-zone-template", Path("zones/authoritative/internal/secondary.conf.tpl"), Path("/etc/named/views/internal/templates/authoritative-secondary.conf.tpl")),
        TemplateArtifact("authoritative-internal-forward-zone-template", Path("zones/authoritative/internal/forward.conf.tpl"), Path("/etc/named/views/internal/templates/authoritative-forward.conf.tpl")),
        TemplateArtifact("authoritative-external-master-zone-template", Path("zones/authoritative/external/master.conf.tpl"), Path("/etc/named/views/external/templates/authoritative-master.conf.tpl")),
        TemplateArtifact("authoritative-external-secondary-zone-template", Path("zones/authoritative/external/secondary.conf.tpl"), Path("/etc/named/views/external/templates/authoritative-secondary.conf.tpl")),
        TemplateArtifact("authoritative-external-forward-zone-template", Path("zones/authoritative/external/forward.conf.tpl"), Path("/etc/named/views/external/templates/authoritative-forward.conf.tpl")),
        TemplateArtifact("proxy-forwarder-internal-master-zone-template", Path("zones/proxy-forwarder/internal/master.conf.tpl"), Path("/etc/named/views/internal/templates/proxy-forwarder-master.conf.tpl")),
        TemplateArtifact("proxy-forwarder-internal-secondary-zone-template", Path("zones/proxy-forwarder/internal/secondary.conf.tpl"), Path("/etc/named/views/internal/templates/proxy-forwarder-secondary.conf.tpl")),
        TemplateArtifact("proxy-forwarder-internal-forward-zone-template", Path("zones/proxy-forwarder/internal/forward.conf.tpl"), Path("/etc/named/views/internal/templates/proxy-forwarder-forward.conf.tpl")),
        TemplateArtifact("proxy-forwarder-external-master-zone-template", Path("zones/proxy-forwarder/external/master.conf.tpl"), Path("/etc/named/views/external/templates/proxy-forwarder-master.conf.tpl")),
        TemplateArtifact("proxy-forwarder-external-secondary-zone-template", Path("zones/proxy-forwarder/external/secondary.conf.tpl"), Path("/etc/named/views/external/templates/proxy-forwarder-secondary.conf.tpl")),
        TemplateArtifact("proxy-forwarder-external-forward-zone-template", Path("zones/proxy-forwarder/external/forward.conf.tpl"), Path("/etc/named/views/external/templates/proxy-forwarder-forward.conf.tpl")),
        TemplateArtifact("proxy-hybrid-internal-master-zone-template", Path("zones/proxy-hybrid/internal/master.conf.tpl"), Path("/etc/named/views/internal/templates/proxy-hybrid-master.conf.tpl")),
        TemplateArtifact("proxy-hybrid-internal-secondary-zone-template", Path("zones/proxy-hybrid/internal/secondary.conf.tpl"), Path("/etc/named/views/internal/templates/proxy-hybrid-secondary.conf.tpl")),
        TemplateArtifact("proxy-hybrid-internal-forward-zone-template", Path("zones/proxy-hybrid/internal/forward.conf.tpl"), Path("/etc/named/views/internal/templates/proxy-hybrid-forward.conf.tpl")),
        TemplateArtifact("proxy-hybrid-external-master-zone-template", Path("zones/proxy-hybrid/external/master.conf.tpl"), Path("/etc/named/views/external/templates/proxy-hybrid-master.conf.tpl")),
        TemplateArtifact("proxy-hybrid-external-secondary-zone-template", Path("zones/proxy-hybrid/external/secondary.conf.tpl"), Path("/etc/named/views/external/templates/proxy-hybrid-secondary.conf.tpl")),
        TemplateArtifact("proxy-hybrid-external-forward-zone-template", Path("zones/proxy-hybrid/external/forward.conf.tpl"), Path("/etc/named/views/external/templates/proxy-hybrid-forward.conf.tpl")),
    )

    @classmethod
    def keys(cls) -> tuple[str, ...]:
        return tuple(artifact.key for artifact in cls.ARTIFACTS)

    @classmethod
    def templates(cls) -> tuple[Path, ...]:
        return tuple(dict.fromkeys(artifact.template for artifact in cls.ARTIFACTS))

    @classmethod
    def destinations(cls, layout: BindLayout) -> tuple[Path, ...]:
        return tuple(artifact.destination(layout) for artifact in cls.ARTIFACTS)

    @classmethod
    def by_key(cls, key: str) -> TemplateArtifact:
        for artifact in cls.ARTIFACTS:
            if artifact.key == key:
                return artifact
        raise KeyError(key)
